### ISSUE TITLE
データベースの構造を決める

### ISSUE THREAD

**Issue by kanako0424** [kanako0424/react_itinerary_app#7]
- firebase realtime database

テーブルはこんな感じ？もっと良い構成ある？（作成中）
ちなみに、場所と場所の経路検索のカードや、候補先のカードも入れたいと思っていたから、旅行の1つ1つの予定はCardと名付けている
Trips
- trip 
  - tripId :string
  - tripTitle : string
  - createdDate : date
  - participantes : [] 
  - cards : {planTitle, planId, participantsInCard, }

Users
- user
  - userId: string（LIFFで取得した文字列）
  - userName: string （LINEのプロフィール情報, 表示名）
  - userPic: string（LINEのプロフィール情報, プロフィール画像のURL）

**Comment by MORIMOTO520212** [comment]
- ざっくりとした理解ですが、こんな感じになりそうでしょうか？
```json
{
  "User": [
    {
      "id": 1,
      "name": "名無しの権兵衛",
      "profile": "",
      "profileImageUrl": "base64",
    },
    {...},
  ],
},
{
  "Trip": [
    {
      "id": 1,
      "title": "",
      "createdAt": "DateTime",
      "participantes": [...],
      "cards": [
        {
          "planTitle": "",
         "planId": "",
         "participantsInCard": "",
        },
        {...},
      ],
    }
  ],
}
```

**Comment by MORIMOTO520212** [comment]
ユーザー情報の管理について、
> liff.getDecodedIDToken()およびliff.getProfile()で取得したユーザーのプロフィールの詳細を、LIFFアプリからサーバーに送信しないでください。
参照：https://developers.line.biz/ja/docs/liff/using-user-profile/#use-user-info-on-server

らしいので、多分、ユーザー情報はトークンだけ保持してプロフィール情報はLINEのAPIから取得するのがよさそうですね

**Comment by kanako0424** [comment]
@MORIMOTO520212 
ごめん、データ構造間違えた。以下のデータ構造が修正版！


1. cardsの中に、日付を表すnumberの数字がある。
2. cardのプロパティは以下11個。


この場合

"Trip": [
    {
      "id": 1,
      "title": "",
      "createdAt": "DateTime",
      "participantes": [...],
      "cards": {
        1: [
        {
          id: uuidv4(),
          destination: "",
          mapLink: "",
          startTime: "",
          endTime: "",
          status: 0,
          reserver: 0,
          reserve: 0,
          participantsInCard: [...],
          notes: "",
          order: 0
        },
        {...}],
       2: [{...}]
      ],
    }
  ],

**Comment by MORIMOTO520212** [comment]
keyを連番IDにする場合、アトミックカウンタが必要そうですね
FirestoreではFieldValue.incrementがサポートされてるらしいんで、それ使いましょう
https://qiita.com/1amageek/items/665df5a6d9921319e300

整形しました
```json
"Trip": [
  {
    "id": 1,
    "title": "",
    "createdAt": "DateTime",
    "participantes": [...],
    "cards": {
      "1": [
         {
           "id": uuidv4(),
           "destination": "",
           "mapLink": "",
           "startTime": "",
           "endTime": "",
           "status": 0,
           "reserver": 0,
           "reserve": 0,
           "participantsInCard": [...],
           "notes": "",
           "order": 0
         },
         {...}
       ],
     "2": [{...}]
   }
],
```

**Comment by kanako0424** [comment]
@MORIMOTO520212 
Tripのidと、cardsのid、どちらも、
uuidv4 （ https://zenn.dev/ttks/articles/f3667048256db0 ）使うのはどうでしょう？
その場合、firestoreのincrementを使用する必要はないってことであっていますか？

#21  のような動きを想定しています！

**Comment by MORIMOTO520212** [comment]
@kanako0424 
そういえば、Tripのcardsの中身ってフロント側で一括で取得する感じでしょうか
その場合、リスト形式にすると扱いやすい気がしてきました

```json
"cards": [{...}, {...}, {...}],
```

**Comment by kanako0424** [comment]
@MORIMOTO520212 

> そういえば、Tripのcardsの中身ってフロント側で一括で取得する感じでしょうか
これもう少し詳しい文章で質問お願いします..!多分そうだと思います。


> リスト形式
以下の認識であっていますか？


`cards[ [{}, {}, {}], [{}, {}, {}], [{}, {}, {}] ] 
`

例）
- cards[1]と指定すると、2日目の予定リストが取得できる
- cards[1][1]と指定すると、2日目の2番目の予定が取得できる。


{}の部分には以下のオブジェクトが入るイメージ
{```

 "id": "uuidv4",
 "destination": "",
 "mapLink": "",
 "startTime": "",
 "endTime": "",
 "status": 0,
 "reserver": 0,
 "reserve": 0,
 "participantsInCard": ["userId1", "userId2"],
 "notes": "",
}
```

**Comment by MORIMOTO520212** [comment]
@kanako0424 
整形してみました
Tripの取得はおそらく1つだけだと思うので、keyをuuidにしてもいいかもしれないです

```json
"Trip": {
  "uuidv4": {
    "id": 1,
    "title": "",
    "createdAt": "DateTime",
    "participantes": ["userId1", "userId2"],
    "cards": [
      [ // 1日目
         {
           "id": "uuidv4",
           "destination": "",
           "mapLink": "",
           "startTime": "",
           "endTime": "",
           "status": 0,
           "reserver": "",    //userId
           "reserve": 0,
           "participantsInCard": ["userId1", "userId2"],
           "notes": "",
         },
         {...}
       ],
       [{...}, {...}] // 2日目
    ]
  }
}
```

**Comment by MORIMOTO520212** [comment]
Userの設計はこちらに書いてます！#30

**Comment by kanako0424** [comment]
@MORIMOTO520212 
データの整形、わかり易すぎて全力感謝です。


`    "id": 1, `

わたしが勘違いしている可能性ありますが、この行は要らないですよね...？


` "createdAt": "DateTime",`

要りますね！ありがとうございます！


`    "participantes": ["userId1", "userId2"],`

スペルは、`participants` ですね!

**Comment by kanako0424** [comment]
firestoreでは、nestされたデータをudpateDocでupdateできないので、objectのほうが扱いやすいやすいかも知れません。

```

"cards": {
      1: [ // 1日目
         {
           "id": "uuidv4",
           "destination": "string",
           "mapLink": "string",
           "startTime": "string",
           "endTime": "string",
           "status": 0,
           "reserver": "string",    //userId
           "reserve": 0,
           "participantsInCard": ["userId1", "userId2"],
           "notes": "string",
         },
         {...}
       ],
       2: [{...}, {...}] // 2日目
    }
```

**Comment by MORIMOTO520212** [comment]
@kanako0424 
firestoreの仕様上、効率的な設計を考えてみました。
提案する内容は以下です。
- cardのIDを`documentId`にしました
- カードの並び替えを、positionプロパティを追加して浮動点小数点で行うようにしました
  - 処理の負荷軽減のため、並び替え対象のカードのみ更新します
- 滞在日をカードごとに管理するようにしました
  - 将来的にカードの日付を変えるユースケースを実装する場合、更新の負荷を減らすため

```json
{
  "user(collection)": {
	  "userId(documentId)": {
		  "lineUserId": "string", // LINEのユーザID U[0-9a-f]{32}
	    "tripHistory": ["tripId", ...], // (実装予定)
	  },
	  "documentId": {...}
  },
  
  "trip(collection)": {
	  "documentId(tripId)": {
	    "title": "string",
	    "createdAt": "DateTime(string)",
	    "participants": ["userId(string)", ...],
	    "card(collection)": {
	      "documentId": {
	          "destination": "string", // 目的地
	          "stayDuration": "number" // 滞在日 ex: 1, 2, 3, 4
	          "mapLink": "string",     // GoogleMapsリンク
	          "startTime": "DateTime(string)",   // 開始時間
	          "endTime": "DateTime(string)",     // 終了時間
	          "status": 0,             // 状態
	          "reserver": "string",    // userId
	          "reserve": 0,            // 予約状況
	          "participantsInCard": ["userId(string)", ...], // 予定参加者
	          "notes": "string",       // メモ
	          "position": "Float(number)" // カードの並びを浮動点少数点で表す position=(前+後)/2
	      },
	    },
	  },
  }
}
```

**Comment by kanako0424** [comment]
@MORIMOTO520212 
ありがとう！！いくつか質問があります！
cardのidをdocumentのidにする方法は良いと思います。
##  stayDurationの変数名について
"duration"はある一定期間の時間を指すと思いますが、今回の場合は、「何日目に訪問するか」を示したいので、stayDay, visitDayのほうが良さそうです。もし今後1つの予定が何日にもまたがることを想定してのことだったらstayDurationという名前で良いと思います！

## カードの並び替えについて(1)
positionを並び替えれば並び替えるほど、positionが細かい値になりそうですが、問題ないでしょうか？ 例えば3枚のカードが並んでいたとします。positionはそれぞれ1,2,3です。positionが3のカードｘをposition1とposition2のカードの間に入れると、カードxの値は1.5になります。このあと、position2のカードyをposition1のカードとカードxの間にいれると、カードyのpositionは、1.25になります。これを何回も繰り返すと、浮動小数点数で表せる数の限界を超えてしまうと思います。chatgptでシミュレーションした結果、float: 約24回目、double: 約50回目の計算で精度を超えるようです。

## カードの並び替えについて(2)
カードが一番後ろや一番前に追加された時は以下のような処理をするという認識ですが合っていますか？カードx,y,zがあります。それぞれのpositionは、1,2,3です。カードxをzの後ろに移動します。この時一番うしろにカードがないので、カードxのpositionは、カードzのpositionに1を加えて3にします。結果 y:1,z:2,x3になります。 反対に、一番前にカードを移動するときは、もともと一番前にあったカードから-1した値をpositionに設定します。

**Comment by kanako0424** [comment]
## カードの並び替えについて（1）補足
positionの値は、整数で大丈夫だと思います。
というのも、私がこのアプリを作り始めた時、最初はcardsはオブジェクト型で、orderというカードの順番を管理するためのプロパティを使っていました。cardの順番を変えるときは、jsのsplice（ https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/splice ）というメソッドを使用していました。

その後、扱いやすいようにcardsは配列型にしよう→だからorderプロパティも削除しよう→firestore使ってみたらネストされたデータ型はupdateできないらしいからcardsをobject型に直そう（今ｺｺ）という話になっているので、positionというプロパティを使用するなら整数型で大丈夫だと思います！（さっきのメッセージの後、なんか同じようなプロパティあったよなぁとふと思い、spliceで順番を操作していたのを思い出しました）

**Comment by MORIMOTO520212** [comment]
@kanako0424 
カードの並び替えに関してなんですけど、浮動点小数点のやり方は、カードの並び替えに限界があ流のはその通りです。
なので、1番初めに作成するカードの`position`の値は大きくする予定です。（例えば: `65535.0`）
ユースケース的に何千回もカードを並び替えることはなさそうかなと思ったので提案しました。

また、Float使うのはバックエンドの責務にしようと思います。フロントに渡す時は整数に振り直して渡します。
逆にフロントからバックに渡す時は、`order`などのプロパティで何番目に入れるかを整数で送ってもらう感じにするのでよいかと思います。

並び替えは以下のサイトを参考にしました。（すみません、貼るの忘れてました）
https://qiita.com/gypsy/items/7bd2a4aeb1b419ce8914
https://www.wantedly.com/companies/wantedly/post_articles/386188

**Comment by kanako0424** [comment]
@MORIMOTO520212 
記事共有ありがとうございます！
なるほど！たしかに複数人で編集する場合を考えるとこっちのほうが良さそうですね。
変数名に関して、`order`は整数感が強いので、`position`という名前でいきましょう。

> また、Float使うのはバックエンドの責務にしようと思います。フロントに渡す時は整数に振り直して渡します。逆にフロントからバックに渡す時は、orderなどのプロパティで何番目に入れるかを整数で送ってもらう感じにするのでよいかと思います。

→承知しました！

**Comment by kanako0424** [comment]
cardsの
destication、nameという名前に変更させて下さい！
「バスに乗る」「自由行動」「飛行場で待つ」などいろんなタイプの予定があるので

**Comment by kanako0424** [comment]
https://docs.google.com/spreadsheets/d/1VgYtac4A0G7dRcmrtFT1EToEX9O3DEJEIEiTpQLhrMU/edit?gid=0#gid=0
